services:
  webapp-container-name:
    image: analytics-api-my-image-name:v1
    build:
      context: .
      dockerfile: Dockerfile-web
    env_file:
      - .env
    ports:
      - "${PORT}:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile-web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yaml
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-pw
      - POSTGRES_DB=timescaledb
    ports:
      - "5434:5432"
    expose:
      - 5434
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
